### ISSUE TITLE
mrv2 can use too much RAM and slow the system down

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#120]
I have 32GB of RAM in my Windows 11 PC. When open a 20 minute long video in mrv2, it starts buffering until the process uses 15GB of RAM, according to task manager. When i open another video to watch them side by side, the new mrv2 instance tries to occupy the same amount of ram. But since i do not have 15GB left, it simply takes as much as it can get, resulting in the system having no free RAM left. In my case this resulted in windows becoming extremely slow, and making me worried that it could crash at any second.

It seems that mrv2 needs to be smarter with its RAM usage. Maybe a setting to let users set a limit could work too.

**Comment by ggarra13** [comment]
You can already control the RAM usage in the Settings Panel->Cache->Gigabytes.  By default it uses half of your RAM but you c an set it to whatever amount you like.
Also it you are *really* short on RAM, you can set the Gigabytes to 0, which will use the Read Ahead / Read Behind setting to control the video RAM usage based in seconds instead of Gygabytes.

**Comment by ggarra13** [comment]
Finally, in the upcoming v0.7.9 version the option to have a Single Instance of mrv2 open will be available.  What that does is that a single mrv2 will run, and any new movies, sequences or images you open will get re-directed to the single instance of mrv2.

**Comment by Thane5** [comment]
Oh interesting, i was not aware that this settings panel existed, but having it does help of course.
