### ISSUE TITLE
OCIO Output Transforms?

### ISSUE THREAD

**Issue by melMass** [ggarra13/mrv2#146]
Hi,

Thanks for mrv2, I stumble on this project yesterday while looking for alternative sequence players and I really like it. I kinda share the points from #132 but not a big deal.
One thing I don't understand is how (if possible) to specify an OCIO output transform when rendering to a video file?

I'm not entirely sure of the current  behaviour

Thanks

**Comment by ggarra13** [comment]
Currently, you cannot specify an OCIO output transform (in Nuke's way of doing it).  

You *can* set your custom config.ocio file in the Preferences->OCIO (F10).  Then that will allow you to select the Input Color Space transform as well as the Display/View transform in the main pull downs of the UI.  When saving a movie file, both transforms are applied to give you a WYIWYG.

**Comment by melMass** [comment]
> both transforms are applied to give you a WYIWYG.

I don't think this is true unfortunately, I naively though so at first but posted the issue after comparing the outputs.
I will try to get a proper repro with a ground truth

**Comment by ggarra13** [comment]
If you are comparing an EXR to a Movie file with the color pipeline, you are likely going to not get a perfect match.  When going to a movie file, you loose precision due to:

- Float (or Half) to 8-bits.
- RGBA to YUV420 (or 444 at best).

However, if you stay in float or half (by reading and saving exrs after going through the pipeline), you should not see visible color differences.

Anyway, if you have an example where this does not hold true, post it here and I'll take a look at it.

**Comment by ggarra13** [comment]
@melMass Were you able to find the problem or get a sample test case?  I am going through the list of bugs before I hit v1.0.0.
