### ISSUE TITLE
Paused video is using %30 cpu of 24 threads constantly

### ISSUE THREAD

**Issue by gerroon** [ggarra13/mrv2#166]
Please see the video. I paused the video, and you can see the activity

```
2 64 bits - v0.9.3 - Built Dec  6 2023 03:01:22
With msvc 1929
(C) 2022-Present Film Aura, LLC.
Gonzalo Garramuño & others
```

https://github.com/ggarra13/mrv2/assets/8519469/9e359310-407f-472b-8df6-d923143d08c2

**Comment by ggarra13** [comment]
I cannot reproduce the problem.

Some questions:

1) Is it a video or a sequence?  Do you have multiple clips loaded or just the one?  With audio or without?
2) Resolution and bit depth of the clip?
3) Any chance you can upload the clip or portion of it privately (send a link to me at ggarra13@gmail.com)?

**Comment by gerroon** [comment]
I can upload the movie (downloaded from youtube) if you have a drive or a space for like 155mb

**Comment by ggarra13** [comment]
I have the disk space.  Feel free to upload it.

**Comment by ggarra13** [comment]
@gerroon I did not get your email.  Were you able to solve your issue?

**Comment by gerroon** [comment]
I do not have that much of email space unfortunately, I need a drop in url, I would be more than hhapy to send it othrwise.

**Comment by ggarra13** [comment]
You should not send the actual file through email, but with a link.  For example, register yourself in a drop site like https://mega.nz.  Upload it there under your name.   Select the file, with the right mouse button select Share Link (or similar).  It will give you a long link.  Copy it and paste it to an email sent to me.  I will be able to access it and download it.

**Comment by ggarra13** [comment]
BTW... How could you tell it was using 24 Threads?  Task Manager does not show the thread count.

**Comment by gerroon** [comment]
https://ufile.io/lpuc072k

It always sues a lot of cpu, it also uses half the cpus whensaving a frame.

**Comment by ggarra13** [comment]
Here's my cpu/memory/gpu usage when stopping a frame.  I have 32GB of RAM, so my cache is set to 15GB.  I show my settings in the video.  You may need to adjust them as needed.


https://github.com/ggarra13/mrv2/assets/6072843/59e74412-d8c2-4ea9-a5bb-e263c1a86193

**Comment by gerroon** [comment]
Interesting, whenever I ipen this video it starts using most of my cpus sometime after I open it. It does not happen right away but takes couple minutes. 

I have been using MRV for a long time, never had this type of high CPU usage.

My cache memory is already set very high. MrV2 is using like 27GB when this video is opened in it.

![image](https://github.com/ggarra13/mrv2/assets/8519469/ad1bbcd4-998a-4ca7-bacd-3aa1d754fbcb)

**Comment by gerroon** [comment]
Here I just tested it again, the cpu usage spiked after 5 mins


https://github.com/ggarra13/mrv2/assets/8519469/30f2c96f-fb94-44ff-91f1-7ecbd390741b

**Comment by ggarra13** [comment]
Some things for you to try to find the problem:

1) Try to set the cache in Gb to 0 only and use Read Ahead/Read Behind instead.  Set Read Behind to a small number like 0.4 and Read Ahead to your heart's content.  I modified the Read Behind setting on recent versions to scrub 4K videos better.
2) If you remember and have time to check, try to locate the version that did not exhibit the problem.   Look them up in sourceforge or in github releases.   That will help a LOT if you locate a version that does not have the problem.

**Comment by gerroon** [comment]
Hi 
I will take a look at those. 

4.) It definitely uses that many cores because my PC fans are going nuts when that happens.

**Comment by ggarra13** [comment]
I was able to reproduce the issue on Linux too, so it is probably an issue common to all platforms.  I will end up pushing the release of v1.0 until the issue can be addressed.  I will be checking all versions previous versions until I find the problem.

**Comment by gerroon** [comment]
Hey thanks for being persistent about this issue. I know it was not easy to hit the bug right away.

**Comment by ggarra13** [comment]
Okay.  I have some clue of what might be happening.  The resampling function from 44100 to 48000 Hz is sometimes misbehaving for 5:1 audio.  I am now investigating if it is a misuse on Darby and mine part of the same.  On the meantime, I tested the original mrViewer and, at least with a good machine like yours, you can play it (I know, mrViewer's GUI sucks, but oh well...).
Hopefully I'll have some news later this week.

**Comment by ggarra13** [comment]
First, the issue on Linux.  The pre-built binaries built on Rocky Linux 8.8 exhibit memory leaks when run on my Ubuntu 22.04.3 LTS box.  If I run it on a Rocky Linux box, there's no leak.  When I compile and run it on Ubuntu 22.04.3 LTS box, there's also no memory leak.

When I run it under a legal version of Windows 11 Pro, I also do not get any leaks or bad cpu usage. 

Do not take the following the wrong way, just be honest when answering:

1) I understand that if you are coming from a non-developed country like mine you sometimes have to sacrifice paying for software to get the best hardware.  Hopefully, you will learn that hurts software developers, as I learnt the hard way too.

2) You uploaded it to a service that does not keep the download anonymous, forcing me to enter a password.  I used google chrome to generate a password. 
 Please change to a service that does not require a password for downloading.

3) You sent me a portion of a movie file for the, I believe, one of the Star Wars tv series.  Since you mention you downloaded it from youtube, and the movie name was imp.mkv.mov, it lead me to believe you used something like the latest version of youtube-dl, instead of subscribing to the YouTube Premium service to download the full movie/clips as that tool downloads the audio and video separately and then merges it.  Technically, the metadata mentioned had HDR support (which mrv2 still does not read or handle) and it said, the handler name  ISO Media file produced by Google Inc, so I could not verify its autenticity.
Currently, the major studios are now they no longer are providing free trailers to download (which I think it is a mistake as it is a way to *promote* their movies, not steal them -- so everybody should win).

4) You mentioned you were using mrv2 v0.9.3, but the screen capture you showed of the Settings Panel, does not look like this:

![image](https://github.com/ggarra13/mrv2/assets/6072843/11786859-8d1a-49e5-86ad-c88cc45ca841)

and instead has the Read Behind is misaligned, which leads me to believe either your file associations are wrong and you are using an older version or something else is amiss.
