### ISSUE TITLE
Preview in DCC 3D Programs ?

### ISSUE THREAD

**Issue by SheepDomination** [ggarra13/mrv2#169]
Is it possible to take a 3D DCC app and have it's previews sent to mrv2 ?
For example, Maya / Houdini all preview renders or even USD could be sent to mrv2.

**Comment by ggarra13** [comment]
Maya, last time I checked, does not provide an API for sending it (the original mrViewer supported outputing from mental ray, but I had to beg and partially reverse engineer the protocol).  Houdini, I've never tried.  USD can be supported through Hydra, albeit the only renderer that seems to be prepared for supporting that *now* is 3Delight, which seems to have a very nice API for doing so.

**Comment by SheepDomination** [comment]
> Maya, last time I checked, does not provide an API for sending it (the original mrViewer supported outputing from mental ray, but I had to beg and partially reverse engineer the protocol). Houdini, I've never tried. USD can be supported through Hydra, albeit the only renderer that seems to be prepared for supporting that _now_ is 3Delight, which seems to have a very nice API for doing so.

How would one do it with Houdini ?
Are you saying that one can send a USD scene with a Hydra render to MRV2; the only problem is restricted with 3Delight, I would like Octane / Renderman support.

**Comment by ggarra13** [comment]
> How would one do it with Houdini ?
> Are you saying that one can send a USD scene with a Hydra render to MRV2; the only problem is restricted with 3Delight, I would like Octane / Renderman support.

Sorry.  I was not clear and I got confused myself. 

You can currently send an .usd scene to mrv2 for rendering (with or without animation), but it will render it with OpenGL only and from the POV of the default camera.  It does not have an Hydra backend support yet.  Darby Johnston was responsible for implementing the USD OpenGL backend.

If we add Hydra support into mrv2, it should be possible to use any of the current renderers, but you would have to install manually the Hydra third-party plugin (usually called render delegates) for your renderer of choice, which, at this point in time, it means compiling it from source.  Prman, 3Delight, Omniverse, Cycles, Solaris and Arnold offer such plugins.  I don't think Octane does yet.
Even if we add Hydra support into mrv2, you would be limited in what you can do with it.  You would still need the DCC application to change materials, move or animate objects again, etc.   Once renderers become real-time as Unreal, hooking Hydra will then become more attractive.

Supporting Hydra with USD is kind of a pain as USD is kind of in flux and uses a mix of very outdated libraries, together with some cutting edge ones.  It also takes more than 25 minutes to build on my 16 cpu machine.  The USD API is great, but the Hydra implementation is a piece of s***, as the demos are all based on python (aaargh!), boost (aaargh!), TBB(aargh!), cutting edge Qt6 (aargh!) or older version of Qt5 (aargh!), which means it breaks on each release and is not fully compatible with modern distros like Ubuntu 22.04.

3Delight in addition to the Hydra backend offers an alternative to USD called NSI, which has partial plugins in all DCCs, it is free to use and link and does NOT depend on Python.  I personally like that approach much better, but it is only used and supported by 3Delight, unfortunately.

**Comment by SheepDomination** [comment]
I wasn't aware that nVidia bought Octane. 
Therefore it should not be impossible for Octane if now owned by nVidia to be integrated ?
There is alot of praise for 3Delight, the render is not new to me, as I've heard of it many years ago. From my knowledge it was comparable to Renderman and it was also praised for its displacement speed if that is still relevant in recent versions is unknown to me. 

For me OpenGL support MRV2 is fine, although full Hydra render in MRV2 would be great but at this time that is only with one render engine. 

How do I send a USD scene to MRV2 though Houdini without having to load it manually ?

**Comment by ggarra13** [comment]
> Therefore it should not be impossible for Octane if now owned by nVidia to be integrated ?

Not likely.  Its future will likely be like that of mental ray/iray.  Kill it and merge the best parts of its source code or logic into Omniverse. 

> For me OpenGL support MRV2 is fine, although full Hydra render in MRV2 would be great but at this time that is only with one render engine.
>

I am afraid you will find mrv2's support still disappointing.  It is barely better than the usdview utility that comes with the USD distribution.  Here's an example of how the ALab scene looks in mrv2 (actually I just opened it again and noticed the new USD looks overblown with lights and much worse than before):

![ALab](https://github.com/ggarra13/mrv2/assets/6072843/6db9e1aa-6693-4a86-8fa6-d3aac1d3fd48)


And here's how it looks in the original Animal Logic's Glimmer renderer:
![LoopySequence02](https://github.com/ggarra13/mrv2/assets/6072843/24eba1ec-3c61-4b23-bb9e-3bc4a2889263)


 
> How do I send a USD scene to MRV2 though Houdini without having to load it manually ?

USD does not support any sort of networking or piping mechanism (that's where Hydra could come in), so the best you can currently do is save out an .usdz (USD zip compressed) file from Houdini, and I'm pretty sure it would allow you to run a python script from inside Houdini to call os.system("mrv2 myanim.usdz").

NVidia with Omniverse and Unreal are working, at least from I gather on demos I see, on supporting USD through the internet, by sending .usdz files instead of the inferior Khronos' gltf format that Meta has invested in.  The idea of Omniverse and Unreal is that you will get full-raytracing, real-time through the network allowing for games and VR on a global scale (ie. imagine every gamer having an NVidia raytracing card to play the latest game or for Googlemaps to be rendered also with raytraced usd cities).  NVidia has a really smart strategy, but the costs and current internet speeds make still prohibitive.

**Comment by ggarra13** [comment]
Here's a tutorial on how to import/export USD in houdini, albeit it does not show how to automate with a script:

https://openusd.org/release/tut_houdini_example.html
