### ISSUE TITLE
Gain and gamma controls before applying Display/View

### ISSUE THREAD

**Issue by jrsndl** [ggarra13/mrv2#171]
It is great to be able to adjust Gamma and Gain controls before applying Display/View to the image.
If that would invalidate the cache, maybe making it optional?
Very useful for tech-checking shots for example.

Thank you

**Comment by ggarra13** [comment]
> It is great to be able to adjust Gamma and Gain controls before applying Display/View to the image. If that would invalidate the cache, maybe making it optional? Very useful for tech-checking shots for example.
> 

AFAIK, gamma and gain are adjusted before OCIO.  Do you see it happening otherwise?  That might be a bug.

Currently the order of shaders is hard-coded in tlRender code.  If you need flexibility from switching from sometimes applying them before and other times applying them after, you should add a feature request with Darby Johnston at:

`https://github.com/darbyjohnston/tlRender/issues`

If it is a feature you need *right now* you may want to look into OpenRV which has a completely flexible shader pipeline.
