### ISSUE TITLE
Frame Numbers move too fast

### ISSUE THREAD

**Issue by Haika-IT** [ggarra13/mrv2#232]
Need a frame number bar at the bottom of the player. That gives all the frame numbers, and highlight the current frame number.

**Comment by ggarra13** [comment]
I am not quite sure I understand.   The speed of the frame number changes based on your FPS setting.  If you want them to move slower, just change your FPS to a lower setting.

The current frame number is shown in white in the timeline bar and in the frame number indicator (the F, S or T to the left of the play buttons -- F for frames, S for seconds, T for timecode).

I agree that movie files without zooming in the timeline viewport indeed don't show as many frame ticks as I would like (it is in my todo list), but frame sequences show them relatively sanely with evenly spaced frame ticks.  Showing **ALL** frame numbers would make them overlap too much.

**Comment by Haika-IT** [comment]
Yes, while playing movie files (.mov or .mp4), the frame number moves too fast. This makes **frame by frame check** to be difficult.

**Comment by ggarra13** [comment]
I imagine English is not your first language, so I am not understanding what you mean.
You can step frame by frame with the buttons  <|  and |>.

**Comment by Haika-IT** [comment]
I can communicate in English properly, it is just that I do not know much of the technical terms in this domain, I am just conveying to you what my colleagues(Artists) are facing trouble with.

**Comment by ggarra13** [comment]
When you report a bug or a problem, you need to provide as much information as possible.  You need to tell me (version of mrv2, platform used, etc.  If you can upload a short movie or picture with the problem, the better.  (if github does not allow you because it is larger than 10Mb or proprietary, upload it to a download place like mega.nz and share the link with an email at ggarra13@gmail.com or just post it here if it is public).  For example, from mega.nz:

https://mega.nz/file/TfgXUCzI#uAZxzZmzl6c47cYHxwECn3DCXkaIKudLuGP1s3u3LlM

There I show all the frame numbers locations (in the timeline and in the left corner).  I show you how to step through frames.
I also show you a preference setting that makes scrubbing through frames faster (maybe that's what they mean), as they scrub with audio.  Turning that preference (Window->Preference->Playback->Auto Scrub Playback) OFF  (it is ON by default) makes movies play without audio while scrubbing but it is easier to scrub frames.  Maybe that's what your Artists mean.
