### ISSUE TITLE
AVI videos do not play

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#283]
Is AVI video meant to work on mrv2? I know that it is slowly dying as format (Which is probably for the better), but i still occasionally run into it. For example, when rendering a video file from Unreal Engine, AVI is still the only supported video codec, at least unless you enable an experimental plugin.

Anyways, here is a good AVI video for testing this whole thing:
[https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_stereo.avi](https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_stereo.avi)

When i try to play this, i get this error in a popup: 
```
ERROR: [] C:\Users\myname\Downloads\big_buck_bunny_720p_stereo.avi: C:\Users\myname\Downloads\big_buck_bunny_720p_stereo.avi: Invalid data found when processing input
```

**Comment by ggarra13** [comment]
AVI videos work fine with mrv2.  AVI is just a container that supports many codecs.  It is the codec that may not be supported.  In order to keep file size small and compilation faster, mrv2 turns off a number of codecs.  If you compile from source, you can turn on ALL codecs.

To find the codec used, you may need to use the ffprobe command-line utility, which you can download from ffmpeg.org.

https://ffmpeg.org/download.html

In the movie you posted, ffprobe lists:

  Stream #0:0: Video: msmpeg4v2 (MP42 / 0x3234504D), yuv420p, 1280x720, 3556 kb/s, 24 fps, 24 tbr, 24 tbn
  Stream #0:1: Audio: mp3 (mp3float) (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 245 kb/s
  
The codec mentioned, msmpeg4v2 (with the FourCC MP42), is an older Microsoft MPEG-4 version 2 codec.  I don't think mrv2 will be supporting that codec.

However, the codec that Unreal uses should be supported as Unreal is in wide use.  Please provide the output of ffprobe for one movie saved from Unreal or send a link to a video for it.

**Comment by ggarra13** [comment]
Unreal uses the "Uncompressed" video codec on .avi files, which is called "rawvideo" in FFmpeg.   That *should* be supported just fine by mrv2.  Please provide a movie file saved from Unreal that does not play on mrv2.

**Comment by Thane5** [comment]
Here is a quick movie, recorded with all the default settings of Unreal Engine 5.4. 
According to VLC, it uses the motion JPEG codec.

[UnrealTest.zip](https://github.com/user-attachments/files/16596823/UnrealTest.zip)
(In case it won't open: This is a .7z that i renamed to .zip because Github won't let me uploade 7-zip archives)

**Comment by ggarra13** [comment]
Sorry it took a while.  Here are Windows betas that should play Unreal movies.

NOTE: The .exe installer now has a new icon for mrv2, so please report if it creates any problems with your installation.

.exe:
https://mega.nz/file/aexiwYaY#guWwZoE3oOKcEao48-HvUppBoi7QQq_yjcHoILZKCLE

.zip:
https://mega.nz/file/CeBXxAqC#2--AI-aWPv6hM3qhXoNQkXDrilVnl9EIZm3t4tBO7V4

**Comment by Thane5** [comment]
Awesome, that works!
